name = "room-management"
main = "src/index.js"
compatibility_date = "2026-07-27"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "room-management-db"
database_id = "GANTI_DENGAN_DATABASE_ID_D1"
