name = "room-management"
main = "src/index.js"
compatibility_date = "2026-07-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "room-management-db"
database_id = "d4c6825e-0b93-43e6-a90c-6f5237a028b5"
